[2022-01-11 18:54:25,885] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-01-11 18:54:25,924] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model scheduled__2022-01-10T00:00:00+00:00 [queued]>
[2022-01-11 18:54:25,924] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 18:54:25,924] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-11 18:54:25,924] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-11 18:54:26,005] {taskinstance.py:1259} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-01-10 00:00:00+00:00
[2022-01-11 18:54:26,015] {standard_task_runner.py:52} INFO - Started process 4693 to run task
[2022-01-11 18:54:26,032] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'scheduled__2022-01-10T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphddfc1a8', '--error-file', '/tmp/tmp5duauj5b']
[2022-01-11 18:54:26,061] {standard_task_runner.py:77} INFO - Job 21: Subtask choose_best_model
[2022-01-11 18:54:26,279] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.choose_best_model scheduled__2022-01-10T00:00:00+00:00 [running]> on host 40c4c8725776
[2022-01-11 18:54:26,542] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-01-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-10T00:00:00+00:00
[2022-01-11 18:54:26,557] {python.py:175} INFO - Done. Returned value was: <Task(BashOperator): accurate>
[2022-01-11 18:54:26,573] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 210, in execute
    raise AirflowException("Branch callable must return either a task ID or a list of IDs")
airflow.exceptions.AirflowException: Branch callable must return either a task ID or a list of IDs
[2022-01-11 18:54:26,604] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=my_dag, task_id=choose_best_model, execution_date=20220110T000000, start_date=20220111T185425, end_date=20220111T185426
[2022-01-11 18:54:26,765] {standard_task_runner.py:92} ERROR - Failed to execute job 21 for task choose_best_model
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 210, in execute
    raise AirflowException("Branch callable must return either a task ID or a list of IDs")
airflow.exceptions.AirflowException: Branch callable must return either a task ID or a list of IDs
[2022-01-11 18:54:26,783] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-11 18:54:27,415] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
